name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      run_apply:
        description: "Do you want to apply the infrastructure?"
        required: true
        default: "no"
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  terraform-apply:
    if: ${{ github.event.inputs.run_apply == 'yes' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Create terraform.tfvars from secrets
        run: |
          echo 'public_subnet_name = "${{ secrets.public_subnet_name }}"' >> terraform.tfvars
          echo 'private_subnet_name = "${{ secrets.private_subnet_name }}"' >> terraform.tfvars
          echo 'sg_name = "${{ secrets.sg_name }}"' >> terraform.tfvars
          echo 'igw_name = "${{ secrets.igw_name }}"' >> terraform.tfvars
          echo 'vpc_name = "${{ secrets.vpc_name }}"' >> terraform.tfvars
          echo 'route_table_name = "${{ secrets.route_table_name }}"' >> terraform.tfvars
          echo 'tg_name = "${{ secrets.tg_name }}"' >> terraform.tfvars
          echo 'load_balancer_type = "${{ secrets.load_balancer_type }}"' >> terraform.tfvars
          echo 'alb_name = "${{ secrets.alb_name }}"' >> terraform.tfvars
          echo 'certificate_arn = "${{ secrets.certificate_arn }}"' >> terraform.tfvars
          echo 'image = "${{ secrets.image }}"' >> terraform.tfvars
          echo 'container_name = "${{ secrets.container_name }}"' >> terraform.tfvars
          echo 'ecs_cluster_name = "${{ secrets.ecs_cluster_name }}"' >> terraform.tfvars
          echo 'capacity_providers = ${{ secrets.capacity_providers }}' >> terraform.tfvars
          echo 'root_domain_name = "${{ secrets.root_domain_name }}"' >> terraform.tfvars

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd infra
          terraform init

      - name: Terraform Apply
        run: |
          cd infra
          terraform apply -auto-approve -var-file=../terraform.tfvars

      - name: Force ECS redeploy
        run: |
         aws ecs update-service --cluster islamable-cluster --service islamable-service --force-new-deployment --region eu-west-2

        
